import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import NavbarMobile from "@/components/navbar/navbar-mobile";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body
      >
         
        <Navbar/>
        <NavbarMobile/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
